#!/bin/bash
VERSION=$(grep "VERSION = " gimp-stable-diffusion.py | sed -E 's/VERSION = "(.+)"/\1/')

TAGVER=$(git tag --list | grep "$VERSION")
if [ "$VERSION" != "$TAGVER" ]; then
  echo "git tag $VERSION; git push --tags"
  echo "is what you need"
  exit 1
fi

ADVERTISING=$(grep version-3 ../stablehorde/version.json | sed -E 's/.* "(.*)",/\1/')

if [ "$VERSION" != "$ADVERTISING" ]; then
  echo "hx ../stablehorde/version.json"
  echo "to update the advertised version"
  exit 1
fi

CHANGE=$(grep "## \[$VERSION\] - " ../CHANGELOG.md | sed -E 's/.*\[(.*)].*/\1/')
if [ "$VERSION" != "$CHANGE" ]; then
  echo "hx ../CHANGELOG.md;git add ../CHANGELOG.md"
  echo "To update the Changelog"
  exit 1
fi

echo gh release upload gimp-stable-diffusion.zip "$VERSION" 
